
# GenAlign Modules Configuration
## Parameters: ['seed', 't_agent', 'agent_weight', 'rf_weight']=(999, 0.1, 0.01, 0.5),
# 1. Intra-modal Alignment (Task A: Image <-> Text)
rf_weight:  0.3 # [0.5, 0.3, 0.1, 0.01] # 0.001 #0.5
# 2. Agent Modality Alignment (Task B: Noise -> ID | Condition)
agent_weight: 0.001 # [0.001, 0.03, 0.05, 0.1] # 0.01       # Fusion weight (alpha)
agent_loss_weight: 0.3 # 1.0 # [0.1, 0.3, 0.5, 0.7] # 1.0   # Loss weight for conditional flow matching
t_agent: 0.5 # [0.1, 0.3, 0.5, 0.7, 0.9]             # Sampling time point (0.9 is close to ID)
agent_step:  [1, 3, 5,10, 50, 100]      # 10      # Number of inference steps (higher is more accurate)
agent_warmup_epochs: 20 # [10, 30, 40, 50] # 20  # Warmup epochs before agent fully intervenes

hyper_parameters: ["agent_step"]

##############################Baby##############################
embedding_size: 64
n_ui_layers: 4 # [3,4]
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-4 # [1e-5,1e-4]
learning_rate: 0.001

cl_loss: 0.01
temperature: 0.2
image_knn_k: 40 # [10,15,20,40]
text_knn_k: 15 # [10,15,20,40]

dropout_rate : 0.1 # [0, 0.1]



# ##############################Sports##############################
# embedding_size: 64
# n_ui_layers: 3 # [3,4]
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-4 # [1e-5,1e-4]
# learning_rate: 0.001

# cl_loss: 0.03
# temperature: 0.2
# image_knn_k: 10 # [10,15,20,40]
# text_knn_k: 10 # [10,15,20,40]

# dropout_rate : 0 # [0, 0.1]

##############################Clothing##############################
# embedding_size: 64
# n_ui_layers: 3 # [3,4]
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-5 # [1e-5,1e-4]
# learning_rate: 0.001

# cl_loss: 0.01
# temperature: 0.2
# image_knn_k: 40 # [10,15,20,40]
# text_knn_k: 10 # [10,15,20,40]

# dropout_rate : 0 # [0, 0.1]


##############################Microlens#############################
# embedding_size: 64
# n_ui_layers: 3 # [3,4]
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-5 # [1e-5,1e-4]
# learning_rate: 0.001

# cl_loss: 0.01
# temperature: 0.2
# image_knn_k: 40 # [10,15,20,40]
# text_knn_k: 10 # [10,15,20,40]

# dropout_rate : 0 # [0, 0.1]


